
[package]
name = "rust_arena_alloc_codegen"
version = "0.1.0"
authors = ["yuyoyuppe <a.yuyoyuppe@gmail.com>"]
edition = "2018"
[profile.release]
panic = "abort"
codegen-units=1
opt-level=3

[dependencies]
typed-arena = "*"
